[package]
name = "rs-services"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
salvo = "0.64.0"
tokio = { version = "1", features = ["macros"] }
tracing = "0.1"
tracing-subscriber = "0.3"

[[bin]]
name = "rs-services"
path = "src/server.rs"